language: node_js
node_js :
 - "node"
after_success: npm run coverage
notifications:
  email:
    on_success: never
    on_failure: never
services:
 - postgresql
before_script:
  - psql -c 'CREATE DATABASE sgcgo_test;' -U postgres
  - psql -c "CREATE USER simon WITH PASSWORD 'pw123';" -U postgres
  - psql -c "ALTER DATABASE sgcgo_test OWNER TO simon;" -U postgres